# Site settings
title: pacodev portafolio
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Francisco Contreras Rodríguez
user_description: A lo largo de 7 años me he desempeñado como desarrollador backend y frontend en BBVA siempre guiándome por los mejores estándares de calidad y utilizando diversas herramientas como las siguientes
projects_description: A si mismo durante este tiempo participe en diversos proyectos entre los que sobresalen los siguientes y que actualmente se encuentran productivos
user_title: Frontend Developer
email: crfranciscocc91@gmail.com
twitter_username: crfranciscocc91
github_username: Francisco914
gplus_username: lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ["package.json", "src", "node_modules"]
